"""Export diagrams to HTML, PNG, SVG."""

import base64
import json
from pathlib import Path


def generate_html_report(
    output_dir: Path,
    repo_name: str,
    diagram_files: list[Path],
    cycles: list[list[str]] | None = None,
) -> Path:
    """Generate standalone HTML report with embedded Mermaid diagrams."""
    html_parts = [
        "<!DOCTYPE html>",
        "<html><head>",
        "<meta charset='utf-8'>",
        "<title>ArchGen - " + repo_name + "</title>",
        "<script src='https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'></script>",
        "<style>",
        "body{font-family:system-ui,sans-serif;margin:2rem;background:#1e1e1e;color:#d4d4d4}",
        "h1{color:#4ec9b0}.diagram{margin:2rem 0;padding:1rem;background:#252526;border-radius:8px}",
        "h2{color:#569cd6;font-size:1.2rem}.cycles{color:#f48771;margin:1rem 0}",
        "pre{background:#1e1e1e;padding:1rem;overflow:auto;border-radius:4px}",
        "a{color:#3794ff}",
        "</style>",
        "</head><body>",
        f"<h1>ArchGen Report: {repo_name}</h1>",
        "<p>Architecture diagrams generated by <a href='https://github.com/sudharshan-nn/archgen'>ArchGen</a></p>",
    ]

    if cycles:
        html_parts.append("<div class='cycles'><h2>⚠️ Circular Dependencies Detected</h2>")
        for c in cycles[:5]:
            html_parts.append(f"<p>{' → '.join(c)} → {c[0]}</p>")
        html_parts.append("</div>")

    for dpath in diagram_files:
        if dpath.suffix != ".mmd":
            continue
        try:
            content = dpath.read_text(encoding="utf-8")
        except Exception:
            continue
        name = dpath.stem.replace("_", " ").title()
        div_id = f"mermaid-{dpath.stem}"
        html_parts.append(f"<div class='diagram'><h2>{name}</h2>")
        html_parts.append(f"<div class='mermaid' id='{div_id}'>")
        html_parts.append(content.replace("<", "&lt;").replace(">", "&gt;"))
        html_parts.append("</div></div>")

    html_parts.extend([
        "<script>mermaid.initialize({startOnLoad:true,theme:'dark'});</script>",
        "</body></html>",
    ])
    report_path = output_dir / "report.html"
    report_path.write_text("\n".join(html_parts), encoding="utf-8")
    return report_path


def export_mermaid_to_image(mmd_path: Path, out_path: Path, fmt: str = "png") -> bool:
    """Export Mermaid to PNG/SVG using mermaid-cli (mmdc). Returns True if success."""
    try:
        import subprocess
        result = subprocess.run(
            [
                "npx", "-y", "@mermaid-js/mermaid-cli",
                "mmdc", "-i", str(mmd_path), "-o", str(out_path),
                "-b", "transparent",
            ],
            capture_output=True,
            timeout=60,
        )
        return result.returncode == 0 and out_path.exists()
    except Exception:
        return False
