"""Export diagrams to HTML, PNG, SVG."""

from pathlib import Path

HTML_TEMPLATE = """<!DOCTYPE html>
<html><head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width,initial-scale=1'>
<title>ArchGen - {repo_name}</title>
<script src='https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'></script>
<style>
*{{box-sizing:border-box}}
body{{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:2rem;background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);color:#e4e4e7;min-height:100vh}}
h1{{color:#38bdf8;font-size:1.8rem;margin-bottom:0.5rem}}
.subtitle{{color:#94a3b8;margin-bottom:2rem}}
.diagrams{{margin-top:2rem}}
.diagram{{margin:2rem 0;padding:1.5rem;background:rgba(30,41,59,0.6);border-radius:12px;border:1px solid rgba(71,85,105,0.5);opacity:0;animation:fadeIn 0.5s ease forwards}}
.diagrams .diagram:nth-child(1){{animation-delay:0.1s}}
.diagrams .diagram:nth-child(2){{animation-delay:0.2s}}
.diagrams .diagram:nth-child(3){{animation-delay:0.3s}}
.diagrams .diagram:nth-child(4){{animation-delay:0.4s}}
.diagrams .diagram:nth-child(5){{animation-delay:0.5s}}
.diagrams .diagram:nth-child(6){{animation-delay:0.6s}}
.diagrams .diagram:nth-child(7){{animation-delay:0.7s}}
.diagrams .diagram:nth-child(8){{animation-delay:0.8s}}
.diagrams .diagram:nth-child(9){{animation-delay:0.9s}}
.diagrams .diagram:nth-child(10){{animation-delay:1s}}
@keyframes fadeIn{{from{{opacity:0;transform:translateY(10px)}}to{{opacity:1;transform:translateY(0)}}}}
.diagram:hover{{background:rgba(51,65,85,0.7);border-color:rgba(99,102,241,0.5);transition:all 0.3s ease}}
.diagram h2{{color:#818cf8;font-size:1.1rem;margin:0 0 1rem 0;display:flex;align-items:center;gap:0.5rem}}
.diagram h2::before{{content:'';width:4px;height:1.2em;background:linear-gradient(180deg,#818cf8,#6366f1);border-radius:2px}}
.mermaid{{display:flex;justify-content:center;overflow:auto;padding:1rem 0}}
.mermaid svg{{max-width:100%}}
.mermaid .edgePath path{{stroke-dasharray:5;animation:flow 2s linear infinite}}
@keyframes flow{{to{{stroke-dashoffset:-10}}}}
.cycles{{background:rgba(239,68,68,0.15);border:1px solid rgba(239,68,68,0.5);border-radius:8px;padding:1rem;margin:2rem 0}}
.cycles h2{{color:#f87171;margin-top:0}}
.cycles p{{margin:0.5rem 0;font-family:monospace;font-size:0.9rem}}
a{{color:#60a5fa;text-decoration:none}}
a:hover{{text-decoration:underline}}
.nav{{margin-bottom:2rem;display:flex;gap:1rem;flex-wrap:wrap}}
.nav a{{background:rgba(99,102,241,0.3);padding:0.5rem 1rem;border-radius:6px;color:#a5b4fc}}
.nav a:hover{{background:rgba(99,102,241,0.5)}}
</style>
</head><body>
<h1>ArchGen Report: {repo_name}</h1>
<p class='subtitle'>Architecture diagrams generated by <a href='https://github.com/sudharshan-nn/archgen'>ArchGen</a></p>
{cycles_html}
<div class='diagrams'>
{diagrams_html}
</div>
<script>
mermaid.initialize({{startOnLoad:true,theme:'dark',themeVariables:{{primaryColor:'#3b82f6',primaryTextColor:'#fff',primaryBorderColor:'#1e40af',lineColor:'#64748b',secondaryColor:'#334155',tertiaryColor:'#1e293b'}}}});
document.querySelectorAll('.diagram').forEach(el=>{{
  el.addEventListener('mouseenter',()=>el.querySelector('.mermaid')?.classList.add('highlight'));
  el.addEventListener('mouseleave',()=>el.querySelector('.mermaid')?.classList.remove('highlight'));
}});
</script>
</body></html>"""


def generate_html_report(
    output_dir: Path,
    repo_name: str,
    diagram_files: list[Path],
    cycles: list[list[str]] | None = None,
) -> Path:
    """Generate standalone HTML report with embedded Mermaid diagrams."""
    cycles_html = ""
    if cycles:
        cycles_html = "<div class='cycles'><h2>⚠️ Circular Dependencies Detected</h2>"
        for c in cycles[:5]:
            cycles_html += f"<p>{' → '.join(c)} → {c[0]}</p>"
        cycles_html += "</div>"

    diagrams_html_parts = []
    for i, dpath in enumerate(diagram_files):
        if dpath.suffix != ".mmd":
            continue
        try:
            content = dpath.read_text(encoding="utf-8")
        except Exception:
            continue
        name = dpath.stem.replace("_", " ").title()
        div_id = f"mermaid-{dpath.stem}"
        escaped = content.replace("<", "&lt;").replace(">", "&gt;")
        diagrams_html_parts.append(
            f"<div class='diagram'><h2>{name}</h2>"
            f"<div class='mermaid' id='{div_id}'>{escaped}</div></div>"
        )

    diagrams_html = "\n".join(diagrams_html_parts)

    html = HTML_TEMPLATE.format(
        repo_name=repo_name,
        cycles_html=cycles_html,
        diagrams_html=diagrams_html,
    )

    report_path = output_dir / "report.html"
    report_path.write_text(html, encoding="utf-8")
    return report_path


def export_mermaid_to_image(mmd_path: Path, out_path: Path, fmt: str = "png") -> bool:
    """Export Mermaid to PNG/SVG using mermaid-cli (mmdc). Returns True if success."""
    try:
        import subprocess
        result = subprocess.run(
            [
                "npx", "-y", "@mermaid-js/mermaid-cli",
                "mmdc", "-i", str(mmd_path), "-o", str(out_path),
                "-b", "transparent",
            ],
            capture_output=True,
            timeout=60,
        )
        return result.returncode == 0 and out_path.exists()
    except Exception:
        return False
